---
title: "couzin_lmer"
output: html_document
---

```{r}
library(lme4)
d = read.csv("~/Repos/couzin_replication/individual-data.csv")
```

```{r}
mod0 = lm(score ~ n_players, data = d)
summary(mod0)
mod0b = lm(score ~ n_players * difficulty, data = d)
summary(mod0b)
(ggplot(d, aes(x = n_players, y = score, col = difficulty, fill = difficulty))#, fill = difficulty))
 + geom_point()
 + stat_summary(fun.y=mean,geom="line", position= 'dodge')
 )
mod1 = lmer(score ~ n_players + (1 | game), data = d)
summary(mod1)
mod2 = lmer(score ~ n_players + (1 | game) + (1 + n_players | noise), data = d)
summary(mod2)
anova(mod1, mod2)
dev_diff <- -2*c(logLik(mod0)-logLik(mod1))
print(dev_diff)
pchisq(dev_diff,1,lower.tail=FALSE) 
```

```{r}
easy_d = subset(d, difficulty == "1en01")
easy_d$pid = factor(easy_d$pid)
easy_d$game = factor(easy_d$game)
easy_d$noise = factor(easy_d$noise)
str(easy_d)
mod0 = lm(score ~ n_players, data = easy_d)
summary(mod0)
mod1 = lmer(score ~ n_players + (1 | game), data = easy_d)
summary(mod1)
mod2 = lmer(score ~ n_players + (1 | game) + (1 + n_players | noise), data = easy_d)
summary(mod2)
anova(mod1, mod2)
dev_diff <- -2*c(logLik(mod0)-logLik(mod1))
print(dev_diff)
pchisq(dev_diff,1,lower.tail=FALSE) 

qplot(x = n_players, y = score, col = noise, data = easy_d)
```

```{r}
med_d = subset(d, difficulty == "2en01")
med_d$pid = factor(med_d$pid)
med_d$game = factor(med_d$game)
med_d$noise = factor(med_d$noise)
mod0 = lm(score ~ n_players, data = med_d)
summary(mod0)
mod1 = lmer(score ~ n_players + (1 | game) + (1 | noise), data = med_d)
summary(mod1)
dev_diff <- -2*c(logLik(mod0)-logLik(mod1))
pchisq(dev_diff,1,lower.tail=FALSE) 
```