---
title: "KeysarMouseTracking.csv"
output: html_document
---

```{r}
setwd('~/Repos/keysar_replication/experiment1/analysis/')
preMouseDExp1 = read.csv('fullSampleMouse.csv')
preErrorDExp1 = read.csv('fullSampleError.csv')
preMessageDExp1 = read.csv('fullSampleMessage.csv')
library(tidyr)
library(dplyr)
library(ggplot2)
```

Set up error data

```{r}
nonCriticalMistakes <- preErrorDExp1 %>%
  # only look at mistakes on noncritical (filler) items
  filter(critical != 1) %>%
  # don't want to double-count people for messing the same thing up multiple times
  filter(attemptNum == 0) %>% 
  group_by(gameid) %>%
  tally() %>%
  # implement exclusion criteria of errors on >~10% of non-critical trials
  filter(n >= 2)

bannedIDsExp1 <- nonCriticalMistakes$gameid
numParticipantsExp1 <- (length(unique(preMouseDExp1$gameid)) -
                        length(bannedIDsExp1))

```

Remove banned ids from data

```{r}
errorDExp1 <- preErrorDExp1 %>%
  filter(!(gameid %in% bannedIDsExp1))
mouseDExp1 <- preMouseDExp1 %>%
  filter(!(gameid %in% bannedIDsExp1))
messageDExp1 <- preMessageDExp1 %>%
  filter(!(gameid %in% bannedIDsExp1))
```

Make error table

```{r}
eDExp1 <- errorDExp1 %>%
  filter(attemptNum == 0) %>%
  group_by(gameid, condition) %>%
  summarize(n = sum(criticalError)) %>%
  mutate(cond1 = as.numeric(n >= 1)) %>%
  mutate(cond2 = as.numeric(n >= 2)) 

errorTableExp1 <- eDExp1 %>% 
  group_by(condition) %>%
  summarise(atLeastOnce = sum(cond1)/numParticipantsExp1, 
            atLeastTwice = sum(cond2)/numParticipantsExp1,
            total = sum(n) / (4 * numParticipantsExp1))
errorTableExp1

# To illustrate how much a few items are driving the effect, we exclude three items 
# where more than 60% of participants made errors.
excludedEDExp1 <- errorDExp1 %>%
  filter(attemptNum == 0) %>%
  filter(!(objectSet %in% c(2, 6, 7))) %>% # Just 5 & 6?
  group_by(gameid, condition) %>%
  summarize(n = sum(criticalError)) %>%
  mutate(cond1 = as.numeric(n >= 1)) %>%
  mutate(cond2 = as.numeric(n >= 2)) %>%
  group_by(condition) %>%
  summarise(atLeastOnce = sum(cond1)/numParticipantsExp1, 
            atLeastTwice = sum(cond2)/numParticipantsExp1,
            total = sum(n) / (4 * numParticipantsExp1))
excludedEDExp1
```

When we look at errors per item, we have to remember that not all items had the same number of participants in the experimental condition.

```{r}
numPlayersPerConditionExp1 = mouseDExp1 %>% 
  filter(critical == 1) %>% 
  filter(attemptNum == 0) %>% 
  group_by(gameid, condition, objectSet) %>% 
  summarize() %>% 
  group_by(condition, objectSet) %>% 
  summarize(total = n()) %>% 
  filter(condition == "exp")
```

Follow-up: are all critical items equal?

```{r}
itemInequalitiesExp1 <- errorDExp1 %>%
  filter(condition == "exp") %>%
  filter(criticalError == 1) %>%
  filter(attemptNum == 0) %>%
  group_by(objectSet) %>%
  tally() %>%
  right_join(numPlayersPerConditionExp1, by = c('objectSet')) %>%
  mutate(objectSet = objectSet,
         errorCount = n, 
         correctCount = total - n) %>%
  mutate(errorRate = errorCount / (errorCount + correctCount)) %>%
  select(objectSet, errorCount, correctCount, errorRate, total)
itemInequalitiesExp1[1,2:4] = c(0, itemInequalitiesExp1[1,]$total, 0)

itemWiseTestExp1 <- chisq.test(itemInequalitiesExp1[-c(1,4,5)])
print(itemWiseTestExp1)
```

Set up mouse/message data

```{r}
mouDataExp1 <- mouseDExp1 %>%
  filter(attemptNum == 0)

mDExp1 <- messageDExp1 %>% 
  filter(attemptNum == 0) %>%
  filter(sender == "director") %>%
  group_by(gameid, objectSet, instructionNum) %>%
  mutate(messageStamp = first(time)) %>%
  select(gameid, condition, attemptNum, instructionNum, critical, objectSet,sender,contents,messageStamp) %>%
  distinct(gameid,contents)

joinedExp1 <- (right_join(mouDataExp1, mDExp1, by = c("gameid", "condition", "objectSet", 
                                         "instructionNum", "attemptNum", "critical")))
```

```{r}
dUnfiltExp1 <- joinedExp1 %>%
  filter(critical == 1) %>%
  group_by(objectSet)

dExp1 <- joinedExp1 %>% 
  filter(critical == 1) %>% 
  group_by(objectSet, condition) %>%
  filter(time > messageStamp) %>%
  mutate(mouseY = 600 - mouseY) %>%
  mutate(targetY = 600 - targetY) %>%
  mutate(begTargetX = first(targetX),
         begTargetY = first(targetY),
         distractorX = as.numeric(levels(distractorX))[distractorX],
         distractorY = 600 - as.numeric(levels(distractorY))[distractorY]) %>%
   mutate(begDistrX = first(distractorX),
          begDistrY = first(distractorY)) %>%
   filter(targetX == begTargetX) %>%
   filter(targetY == begTargetY) %>%
   filter(distractorX == begDistrX) %>%
   filter(distractorY == begDistrY) 

```

Compute hover time statistics

```{r}

sem <- function(x) {sd(x, na.rm = T) / sqrt(length(x))}
ci95 <- function(x) {sem(x) * 1.96}

heatMapForLMExp1 <- dExp1 %>%
  group_by(gameid, objectSet) %>%
  mutate(inTargetSquare = as.numeric(mouseX > targetX - 75 
                                     & mouseX < targetX + 75
                                     & mouseY > targetY - 75
                                     & mouseY < targetY + 75)) %>%
  mutate(inDistractorSquare = as.numeric(mouseX > distractorX - 75
                                         & mouseX < distractorX + 75
                                         & mouseY > distractorY - 75
                                         & mouseY < distractorY + 75)) %>%
  group_by(gameid, condition) %>%
  summarise(distractor = sum(inDistractorSquare) / n(),
         target = sum(inTargetSquare) / n()) %>%
  gather(cellType, percent, distractor, target) 

heatMapForLMExp1

t1 <- lm(percent ~ condition * cellType, data = heatMapForLMExp1)
summary(t1)
```

Plot it? 

```{r}
heatMapForPlotExp1 <- dExp1 %>%
  group_by(gameid, objectSet) %>%
  mutate(inTargetSquare = as.numeric(mouseX > targetX - 75 
                                     & mouseX < targetX + 75
                                     & mouseY > targetY - 75
                                    & mouseY < targetY + 75)) %>%
  mutate(inDistractorSquare = as.numeric(mouseX > distractorX - 75
                                         & mouseX < distractorX + 75
                                         & mouseY > distractorY - 75
                                         & mouseY < distractorY + 75)) %>%
  group_by(gameid, condition) %>%
  summarize(distractor = sum(inDistractorSquare) / n(),
         target = sum(inTargetSquare) / n()) %>%
  gather(cellType, percent, distractor, target) %>%
  group_by(condition, cellType) %>%
  summarize(error = sem(percent),
            percent = mean(percent)) 
  
heatMapForPlotExp1

g <- (ggplot(heatMapForPlotExp1, aes(x = condition, y = percent, group = cellType,
                                  color = cellType)) 
      + geom_line(aes(linetype = cellType), size = 2)
      + geom_errorbar(aes(ymax = percent + error, 
                          ymin = percent - error), size =2 ,
                      width = 0.1)
      + ylim(0,.45)
      + ggtitle("Experiment 1 Hover-Time"))
g
ggsave("../../writing/cogsci-submission/images/exp1MouseTracking.pdf")
```

Very noisy (unfinished) plot of all mouse-movements

```{r}
# heatMapForPlot$new_labels = as.factor(sapply(X = heatMapForPlot$objectSet, 
#                               FUN = function(v) {return(paste("Item", v))}))
# 
# g <- (ggplot(heatMapForPlot, aes(x = mouseX, y = mouseY, color = condition)) +
#       geom_vline(xintercept = c(0, 150,300,450, 600)) +
#       geom_hline(yintercept = c(0, 150,300,450, 600)) +
#       geom_point() +
#       geom_point(aes(x = begTargetX, y = begTargetY), size = 20,
#                  shape = 4, color = "black", show_guide = FALSE) +
#       geom_point(aes(x = begDistrX, y = begDistrY), size = 20,
#                  shape = 4, color = "grey50", show_guide = FALSE) + 
#       theme(panel.grid.major = element_blank(), 
#             panel.grid.minor = element_blank()) +
#       xlim(0, 600) +
#       ylim(0, 600) +
#       theme(aspect.ratio = 1) +
#       facet_wrap(~ new_labels, nrow = 2))
# g
```