---
title: "R Notebook"
output: html_notebook
---

# General imports

```{r}
library(jsonlite)
library(tidyverse)
library(ggthemes)
library(lme4)
library(lmerTest)
```

# Experiment 2

## Import turk survey data 

```{r}
path <- "../data/final/experiment2/planned_sample/turk/"
files = dir(path, pattern = "*.json")

subjInfo = data.frame()

for (f in files) {
  jf = paste0(path, f)
  jd = read_json(jf)
  
  newRow = data.frame()
  if(!is.null(jd$answers$subject_information)) {
    # for(property in names(jd$answers$subject_information) {
    #   if(!is.null(jd$answers$subject_information[property])) {
    #     newRow[property] = jd$answers$subject_information[property]
    #   } else 
    #     newRow[property] = NA
    # }
    newRow = data.frame(gameid = jd$answers$subject_information$gameID,
                        role = jd$answers$subject_information$role,
                        gameLength = jd$answers$subject_information$totalLength,
                        thinksHuman = ifelse(!is.null(jd$answers$subject_information$thinksHuman), jd$answers$subject_information$thinksHuman, NA),
                        understandsInstructions = jd$answers$subject_information$confused,
                        nativeEnglish = jd$answers$subject_information$nativeEnglish,
                        ratePartner = jd$answers$subject_information$ratePartner,
                        comments = jd$answers$subject_information$comments,
                        strategy = jd$answers$subject_information$strategy)
    subjInfo = bind_rows(subjInfo, newRow)
  }
}


```

## Import message data

```{r}
d_raw <- read_tsv('../data/final/experiment2/planned_sample/chatMessage/message.csv') %>%
  filter(iterationName == 'planned_sample') %>%
  filter(role == 'speaker')

# nonNativeSpeakerIDs <- unique((tangramSubjInfo %>% filter(nativeEnglish != "yes"))$gameid)
incompleteIDs <- unique((d_raw %>% group_by(gameid) %>% 
                           filter(length(unique(trialNum)) != 24))$gameid)
confused <- unique((subjInfo %>% filter(understandsInstructions != 'yes'))$gameid)

# Some speakers relied on location in grid
location_abusers <- c('8219-bb7861c1-43f4-480c-906b-8441c583c0ab', '7726-3d4a266f-e56d-4afb-9a79-b40deb690a76', '5684-f09de856-4d64-423c-b342-b30e7325eb0e', '7600-346d56b5-bd76-406f-befb-6b47e07d5916')
badGames <- c(incompleteIDs, pureLocation, confused)

d <- d_raw %>%
  group_by(gameid, trialNum, occlusions, context) %>%
  summarize(text = paste0(text, collapse = ' ')) %>%   # Concatenate multiple utterance on same trial
  mutate(numRawWords = str_count(text, "\\S+")) %>%
  mutate(hidden = ifelse(occlusions == 'none', 'no', 'yes')) %>%
  filter(!(gameid %in% badGames))
```

## Check basic (no-hidden) pragmatic effect

```{r}
basic.d <- d %>%
  filter(hidden == 'no') %>%
  group_by(gameid, context) %>%
  summarize(m = mean(numRawWords)) %>%
  spread(context, m) %>%
  mutate(diff = close- far,
         ratio = close / far)
 
ggplot(basic.d, aes(x = far, y = close)) +
    geom_point() +
    theme_bw() +
    geom_abline(intercept = 0, slope = 1) +
    ylim(1,12) +
    xlim(1,12) +
    theme(aspect.ratio = 1)
```

Aggregated to difference scores:

```{r}
ggplot(basic.d, aes(x = diff)) +
    geom_histogram(binwidth = 0.25) +
    theme_bw() +
    geom_vline(xintercept = 0) +
    # ylim(1,12) +
    xlim(-4,4) +
    theme(aspect.ratio = 1)

t.test(basic.d$diff)
```

## Message length collapsing across all subjects

```{r}
dodge <- position_dodge(width=0.9)

d %>%
  group_by(context, hidden) %>%
  summarize(m = mean(numRawWords), se = sd(numRawWords)/sqrt(length(numRawWords))) %>%
  ggplot(aes(x = hidden, y = m, fill = context)) +
    geom_bar(stat = 'identity', position = dodge) +
    geom_errorbar(aes(ymin = m - se, ymax = m + se), position = dodge, width = 0.1) +
    theme_bw()
```

## Scatter to look at within-subj effects

```{r}
hidden.d <- d %>%
  group_by(gameid, context, hidden) %>%
  summarize(m = mean(numRawWords)) %>%
  spread(hidden, m) %>%
  mutate(diff = yes- no) 

ggplot(hidden.d, aes(x = no, y = yes)) +
    geom_point() +
    facet_wrap(~ context) +
    theme_bw() +
    geom_abline(intercept = 0, slope = 1) +
    ylim(1,15) +
    ylab('# words (with occlusions)') +
    xlab('# words (without occlusions)') +
    ggtitle('Within-pair comparisons of reference w/ and w/out occlusion') +
    xlim(1,15) +
    theme(aspect.ratio = 1)

ggsave('~/Downloads/scatter.pdf')
```

Histogram

```{r}
ggplot(hidden.d %>% group_by(context) %>% mutate(m = mean(diff)), aes(x = diff)) +
    geom_histogram(binwidth = 0.33) +
    theme_bw() +
    geom_vline(xintercept = 0, linetype = 2) +
    geom_vline(aes(xintercept = m), color = 'red') +
    facet_wrap(~ context) +
    # ylim(1,12) +
    xlim(-6,6) +
    theme(aspect.ratio = 1)

ggsave("~/Downloads/histograms.pdf")
```

```{r}
hidden.d %>%
  group_by(context) %>%
  summarize(m = mean(diff), se = sd(diff)/sqrt(length(diff))) %>%
  ggplot(aes(x = context, y = m)) +
    geom_bar(stat = 'identity') +
    geom_errorbar(aes(ymin = m - se, ymax = m + se), width = 0) +
    theme_few() +
    ylim(-3, 3) +
    ylab('# words (occlusions - no occlusions)')
  
```

Clusters

```{r}
hidden.d %>% 
  filter(context == 'far') %>% 
  mutate(group = case_when(diff < -0 ~ 'anti',
                           diff > 0 ~ 'pro',
                           TRUE ~ 'all_the_things')) %>%
  group_by(group) %>% tally()
```

# Stats

Simple effect of hidden-ness in 'far' contexts 

```{r}
summary(lmer(numRawWords ~ hidden + (1 + hidden | gameid), 
             data = d %>% 
                filter(context == 'far')))
t.test(numRawWords ~ hidden, data = d %>% filter(context == 'far'), var.equal = FALSE)
```

interaction-y way

```{r}
summary(lmer(numRawWords ~ context * hidden + (1 + context * hidden | gameid), data = d))
```

helmert coding way (one way of slicing)

```{r}
d.regression <- d %>% 
  unite(condition, context, hidden) %>%
  ungroup() %>%
  mutate(condition = ordered(condition, levels = c('far_no', 'close_no', 'far_yes', 'close_yes')))
contrasts(d.regression$condition) <- contr.helmert(4)
summary(lmer(numRawWords ~ condition + (1 + condition | gameid), data = d.regression))
```

